import clsx from 'clsx'
import type { Metadata } from 'next'
import { Ubuntu, Noto_Sans_JP } from 'next/font/google'
import { DictInstance } from '@/types'
import ButtonGroup from '@/ui/btn-group'
import Link from '@/ui/link'
import './globals.scss'

const ubuntu = Ubuntu({
  weight: ['400', '700'],
  subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
  variable: '--ubuntu'
})

const notoSansJP = Noto_Sans_JP({
  weight: ['400', '700'],
  subsets: [],
  variable: '--noto-sans-jp'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={clsx(ubuntu.className, ubuntu.variable, notoSansJP.variable)}>
        <header>
          <ButtonGroup>
            <Link href="/collections" type="button" ja="コレクション">
              Collection
            </Link>
            <Link href="/kana" type="button" ja="仮名">
              Kana
            </Link>
            <Link href="/lyrics" type="button" ja="作詞">
              Song lyrics
            </Link>
            <Link href="/novels" type="button" ja="小説">
              Novels
            </Link>
          </ButtonGroup>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
